// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATonh4EXgkehLvdHtdFSzIaP1qUOZ52OQ',
    appId: '1:251494050169:web:b1b8fb56ad96fef67127a8',
    messagingSenderId: '251494050169',
    projectId: 'reon-e0090',
    authDomain: 'reon-e0090.firebaseapp.com',
    storageBucket: 'reon-e0090.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGPHHI73udbkzYenryOusmiPgsmRBcJo',
    appId: '1:251494050169:android:9c467edda07ebb957127a8',
    messagingSenderId: '251494050169',
    projectId: 'reon-e0090',
    storageBucket: 'reon-e0090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8wshATibNpOET-5GmFEtMFFR0iYZgks',
    appId: '1:251494050169:ios:9b153e7f78386a087127a8',
    messagingSenderId: '251494050169',
    projectId: 'reon-e0090',
    storageBucket: 'reon-e0090.appspot.com',
    iosBundleId: 'com.example.task3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk8wshATibNpOET-5GmFEtMFFR0iYZgks',
    appId: '1:251494050169:ios:231aa6777f356b067127a8',
    messagingSenderId: '251494050169',
    projectId: 'reon-e0090',
    storageBucket: 'reon-e0090.appspot.com',
    iosBundleId: 'com.example.task3.RunnerTests',
  );
}
